In [3]:
import koco
from Korpora import Korpora

In [4]:
Korpora.fetch("korean_hate_speech", root_dir='./korpora')

[korean hate speech] download unlabeled_comments_1.txt: 57.0MB [00:00, 71.9MB/s]                            
[korean hate speech] download unlabeled_comments_2.txt: 59.3MB [00:00, 72.6MB/s]                            
[korean hate speech] download unlabeled_comments_3.txt: 58.9MB [00:00, 72.1MB/s]                            
[korean hate speech] download unlabeled_comments_4.txt: 58.2MB [00:00, 72.1MB/s]                            
[korean hate speech] download unlabeled_comments_5.txt: 3.57MB [00:00, 11.8MB/s]                            
[korean hate speech] download unlabeled_comments.news_title_1.txt: 44.7MB [00:00, 65.1MB/s]                            
[korean hate speech] download unlabeled_comments.news_title_2.txt: 47.4MB [00:00, 66.9MB/s]                            
[korean hate speech] download unlabeled_comments.news_title_3.txt: 48.5MB [00:00, 68.7MB/s]                            
[korean hate speech] download unlabeled_comments.news_title_4.txt: 47.9MB [00:00, 64.0MB/s]    

In [5]:
train_dev = koco.load_dataset('korean-hate-speech', mode='train_dev')

train_comments: list[str] = []
gender_list: list[bool] = []
bias_list: list[str] = []
hate_list: list[str] = []
title_list: list[str] = []

for dict in train_dev['train']:
    train_comments.append(dict['comments'])
    gender_list.append(dict['contain_gender_bias'])
    bias_list.append(dict['bias'])
    hate_list.append(dict['hate'])
    title_list.append(dict['news_title'])

In [6]:
test_dict = koco.load_dataset('korean-hate-speech', mode='test')
test_comments: list[str] = []
test_titles: list[str] = []

for dict in test_dict:
    test_comments.append(dict['comments'])
    test_titles.append(dict['news_title'])

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# label 인코딩은 선형회귀에서 사용하면 안 됨.
# One-hot 인코딩 필요

le = LabelEncoder()
train_encoded = le.fit_transform(train_comments)
test_encoded = le.transform(test_comments)
print(train_encoded)

# 2차원 데이터 변환
train_encoded = train_encoded.reshape(-1, 1)
test_encoded = test_encoded.reshape(-1, 1)
print(train_encoded)

# One-hot Encoding
oh = OneHotEncoder()
train_onehot = oh.fit_transform(train_encoded)
test_onehot = oh.transform(test_encoded)
print(train_onehot.toarray())

lr = LogisticRegression()
lr.fit(train_onehot, gender_list)

"""
items = pd.DataFrame(['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], columns=['items'])
print(items)

pd.get_dummies(items)
https://2-chae.github.io/category/1.ai/30
"""

def refine(comment: str):
    data = [comment]
    le = LabelEncoder()
    encoded = le.transform(data).reshape(-1, 1)
    oh = OneHotEncoder()
    onehot = oh.transform(encoded)
    return onehot

print(test_onehot)
lr.predict(test_onehot)

[[   0]
 [   3]
 [   4]
 ...
 [8866]
 [8867]
 [8868]]
[[ 273]
 [2436]
 [1127]
 [6036]
 [7107]
 [4266]
 [2023]
 [8429]
 [7835]
 [4349]
 [7902]
 [4683]
 [ 863]
 [4833]
 [3229]
 [ 687]
 [7985]
 [1193]
 [5265]
 [7624]
 [1359]
 [3704]
 [3735]
 [6639]
 [8588]
 [6183]
 [8324]
 [4722]
 [ 958]
 [8093]
 [5188]
 [3862]
 [7596]
 [1508]
 [3712]
 [3664]
 [8486]
 [ 397]
 [7458]
 [8408]
 [4063]
 [1007]
 [ 489]
 [1567]
 [4936]
 [3878]
 [5815]
 [2815]
 [ 741]
 [ 643]
 [5277]
 [2043]
 [8281]
 [2854]
 [4154]
 [4499]
 [3842]
 [ 198]
 [8113]
 [ 711]
 [2702]
 [ 343]
 [7335]
 [2216]
 [ 178]
 [5958]
 [4367]
 [  86]
 [6068]
 [4186]
 [6008]
 [ 612]
 [3230]
 [1109]
 [1412]
 [  83]
 [6019]
 [5156]
 [5798]
 [5591]
 [5562]
 [6565]
 [8207]
 [ 429]
 [2071]
 [1049]
 [8208]
 [3014]
 [3825]
 [7436]
 [ 526]
 [  99]
 [1254]
 [2425]
 [6822]
 [6835]
 [2381]
 [8385]
 [5890]
 [4564]
 [1662]
 [1142]
 [5291]
 [ 532]
 [6109]
 [3540]
 [4350]
 [5892]
 [7479]
 [3901]
 [8672]
 [1729]
 [5553]
 [5794]
 [4580]
 [8080]
 [7914]
 [1288]
 [

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,